const AWS_S3_REGION = process.env.AWS_S3_REGION;
const AWS_S3_ACCESS_KEY_ID = process.env.AWS_S3_ACCESS_KEY_ID;
const AWS_S3_SECRET_ACCESS_KEY = process.env.AWS_S3_SECRET_ACCESS_KEY;
const AWS_S3_BUCKET_NAME = process.env.AWS_S3_BUCKET_NAME;

exports.AWS_S3_REGION = AWS_S3_REGION;
exports.AWS_S3_ACCESS_KEY_ID = AWS_S3_ACCESS_KEY_ID;
exports.AWS_S3_SECRET_ACCESS_KEY = AWS_S3_SECRET_ACCESS_KEY;
exports.AWS_S3_BUCKET_NAME = AWS_S3_BUCKET_NAME;
